"""empty message

Revision ID: 7999b07e44e2
Revises: 0b0f5fae0db5
Create Date: 2022-04-12 13:49:00.134111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7999b07e44e2'
down_revision = '0b0f5fae0db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
