"""empty message

Revision ID: 819affafa30b
Revises: 7999b07e44e2
Create Date: 2022-04-12 13:53:50.278306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819affafa30b'
down_revision = '7999b07e44e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_profile_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'profile_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_profile_id_fkey', 'posts', 'profiles', ['profile_id'], ['id'])
    # ### end Alembic commands ###
